Add director
smmhubru/java-filmorate pull request #15
Opened 2022-06-30 07:26 UTC by Sadaaaaa

Added film director feature

2022-06-30 14:08 UTC, smmhubru commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    // Список всех режиссёров
из названия функции уже понятно что она делает, комментарий лишний

2022-06-30 14:17 UTC, smmhubru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        String sqlQuery = "SELECT * FROM films AS f LEFT JOIN film_directors AS fd ON fd.film_id = f.film_id LEFT JOIN directors AS d ON fd.director_id = d.director_id";
Звездочки в SQL запросе не лучшая практика, в случае изменения состава полей придется менять код класса.

2022-06-30 14:18 UTC, smmhubru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        String sqlQuery = "SELECT * FROM ratings";
Лучше обозначить конкретный состав требуемых полей вместо звездочки.

2022-06-30 14:23 UTC, smmhubru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorDao.java
> +        if(sortBy.equals("year")) {
Оператор switch возможно был бы уместнее

2022-06-30 14:24 UTC, smmhubru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorDao.java
> +        String sql = "SELECT * FROM directors WHERE director_id = ?";
Звездочку лучше заменить на указание конкретных полей.

2022-06-30 14:25 UTC, smmhubru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorDao.java
> +        return jdbcTemplate.queryForObject("SELECT * FROM directors WHERE director_name = ?", new MapRowToDirector(), director.getName());
по звездочке аналогично

2022-06-30 14:27 UTC, smmhubru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorDao.java
> +    public void deleteDirectorById(int id) {
можно использовать `directorId` вместо `id` для лучшей читабельности, в целом лучше избегать общеупортебимых название переменных вроде `id`

2022-06-30 14:28 UTC, smmhubru commented on src/main/java/ru/yandex/practicum/filmorate/storage/mapper/MapRowToFilm.java
> +    public Film mapRow(ResultSet resultSet, int rowNum) throws SQLException {
Дублирование кода в двух класса, вынос в отдельный класс маппера для фильма ок, но тогда нужно выпилить его из самого класса

2022-06-30 14:28 UTC, smmhubru commented on src/main/java/ru/yandex/practicum/filmorate/storage/mapper/MapRowToGenre.java
> +public class MapRowToGenre implements RowMapper<Genre> {
Аналогично, дублирование кода, оставить где-то в одном из классов.

2022-06-30 14:29 UTC, smmhubru commented on src/main/resources/application.properties
> +spring.datasource.password=
пароль бы все таки оставил даже на тестовой базе

2022-06-30 14:34 UTC, smmhubru commented on src/main/resources/schema.sql
> +drop table IF EXISTS EVENTS;
Очистка базы перед созданием таблиц, ок. Но не надо ломать старое форматирование, привести к оригиналу в соответствии с [https://www.sqlstyle.guide/ru/](https://www.sqlstyle.guide/ru/)

2022-06-30 14:35 UTC, smmhubru requested changes
Хорошая работа, небольшие доработки по структуре и сбито SQL форматирование.

2022-06-30 16:54 UTC, Sadaaaaa commented on src/main/resources/application.properties
> +spring.datasource.password=
с паролем не работает приложение, я спрашивал почему в слаке - не помогли

2022-06-30 17:33 UTC, Sadaaaaa commented on src/main/java/ru/yandex/practicum/filmorate/storage/mapper/MapRowToFilm.java
> +    public Film mapRow(ResultSet resultSet, int rowNum) throws SQLException {
- второй маппер (который в классе) лучше оставить, потому что без него ломаются старые тесты
- наставник предложил `new BeanPropertyRowMapper<>(Film.class)`, но это не везде решает проблему
- можно вынести маппер из ДАО класса в отдельный класс (без режиссеров), но дублирования не избежать
- предлагаю либо забить, либо оставить до рефакторинга

2022-07-01 00:39 UTC, smmhubru requested changes
- бинарный файл `filmorate.mv.db` и `filmorate.trace.db` нужно убрать из проекта, они подлежат формированию на клиентской машине

2022-07-01 00:39 UTC, smmhubru commented on src/main/resources/schema.sql
> +    event_pk_id        integer   NOT NULL,
поле `event_pk_id` не нужно и отсутствует в оригинальном файле

2022-07-02 08:28 UTC, merged