Add search
smmhubru/java-filmorate pull request #16
Opened 2022-06-30 14:34 UTC by Sadaaaaa

2022-06-30 14:41 UTC, smmhubru commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    // Удаление режиссёра
самоочевидные комментарии, можно удалить

2022-06-30 14:44 UTC, smmhubru commented on src/main/java/ru/yandex/practicum/filmorate/model/FilmDirector.java
> +public class FilmDirector {
Модели `Film` и `Director` уже есть. Связка FilmDirector имеет смысл только на уровне хранилища для создания отношения многие ко многим, подумать на счет целесообразности класса.

2022-06-30 14:45 UTC, smmhubru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        String sqlQuery = "SELECT * FROM films AS f LEFT JOIN film_directors AS fd ON fd.film_id = f.film_id LEFT JOIN directors AS d ON fd.director_id = d.director_id";
звездочки зло

2022-06-30 14:46 UTC, smmhubru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        String sqlQuery = "SELECT * FROM ratings";
звездочки зло

2022-06-30 14:46 UTC, smmhubru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +            String sqlSearchByName = "SELECT * FROM films AS f " +
звездочки )

2022-06-30 14:47 UTC, smmhubru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        for (Film y : result) {
Возможно, цикл можно заменить на stream.forEach()

2022-06-30 14:47 UTC, smmhubru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorDao.java
> +        String sql = "SELECT * FROM films AS f " +
звездочки

2022-06-30 14:48 UTC, smmhubru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorDao.java
> +        if(sortBy.equals("year")) {
switch

2022-06-30 14:48 UTC, smmhubru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorDao.java
> +        return jdbcTemplate.queryForObject("SELECT * FROM directors WHERE director_name = ?", new MapRowToDirector(), director.getName());
звездочки

2022-06-30 14:48 UTC, smmhubru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorDao.java
> +        String sql = "SELECT * FROM directors WHERE director_id = ?";
звездочки

2022-06-30 14:49 UTC, smmhubru commented on src/main/resources/schema.sql
> +drop table IF EXISTS EVENTS;
сломано оригинальное форматирование

2022-06-30 14:49 UTC, smmhubru requested changes
Nice work, небольшие правки по SQL

2022-06-30 15:36 UTC, Sadaaaaa commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        for (Film y : result) {
со стримом не вышло
только если подскажешь как

2022-07-02 08:53 UTC, smmhubru requested changes
Обновиться от main, разрешить конфликты.

2022-07-02 13:53 UTC, smmhubru requested changes
Pr затирает правки по прошлому pr

2022-07-02 13:53 UTC, smmhubru commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +
Самоочевидные комментарии.

2022-07-02 13:53 UTC, smmhubru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +        String sqlQuery = "SELECT * FROM ratings";
вернулись звездочки

2022-07-02 13:53 UTC, smmhubru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +
мертвый код

2022-07-02 13:53 UTC, smmhubru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DbFilmStorage.java
> +                String sqlSearchByName = "SELECT * FROM films AS f " +
вернулись звездочки

2022-07-02 13:53 UTC, smmhubru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorDao.java
> +        String sql = "SELECT * FROM films AS f " +
звездочки

2022-07-02 13:53 UTC, smmhubru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorDao.java
> +        String sql = "SELECT * FROM directors WHERE director_id = ?";
звездочки

2022-07-02 13:53 UTC, smmhubru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorDao.java
> +        return jdbcTemplate.queryForObject("SELECT * FROM directors WHERE director_name = ?", new MapRowToDirector(), director.getName());
звездочки

2022-07-02 13:53 UTC, smmhubru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DirectorDao.java
> +        jdbcTemplate.update(sqlDeleteDirector, id);
старое наименование функции

2022-07-02 13:53 UTC, smmhubru commented on src/main/resources/schema.sql
> +                                       rating_id           integer         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
сломано SQL форматирование

2022-07-02 14:27 UTC, smmhubru approved these changes
Looks nice

2022-07-02 14:27 UTC, merged